### ISSUE TITLE
Got errors "X11 is not available" and "FileNotFoundError: [Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by myliu221** [stjude/ROSE#11]
Hi,
I installed ROSE-1.3.0, ran super enhancer analysis and got errors as following
Error in png(filename = plotFileName, height = 600, width = 600) :
  X11 is not available
Execution halted
Traceback (most recent call last):
  File "/home/mingyu.liu001/Software/ROSE-1.3.0/bin/ROSE_geneMapper.py", line 291, in <module>
    main()
  File "/home/mingyu.liu001/Software/ROSE-1.3.0/bin/ROSE_geneMapper.py", line 277, in main
    enhancerToGeneTable,geneToEnhancerTable = mapEnhancerToGene(annotFile,enhancerFile,uniqueGenes=True,byRefseq=options.refseq, transcribedFile=transcribedFile)
  File "/home/mingyu.liu001/Software/ROSE-1.3.0/bin/ROSE_geneMapper.py", line 36, in mapEnhancerToGene
    enhancerTable = ROSE_utils.parseTable(enhancerFile,'\t')
  File "/home/mingyu.liu001/Software/ROSE-1.3.0/lib/ROSE_utils.py", line 45, in parseTable
    fh = open(fn)
FileNotFoundError: [Errno 2] No such file or directory: './EHMT1_ctrl//EHMT1_ctrl_merged_peaks_SuperStitched.table.txt'
Traceback (most recent call last):
  File "/home/mingyu.liu001/Software/ROSE-1.3.0/bin/ROSE_geneMapper.py", line 291, in <module>
    main()
  File "/home/mingyu.liu001/Software/ROSE-1.3.0/bin/ROSE_geneMapper.py", line 277, in main
    enhancerToGeneTable,geneToEnhancerTable = mapEnhancerToGene(annotFile,enhancerFile,uniqueGenes=True,byRefseq=options.refseq, transcribedFile=transcribedFile)
  File "/home/mingyu.liu001/Software/ROSE-1.3.0/bin/ROSE_geneMapper.py", line 36, in mapEnhancerToGene
    enhancerTable = ROSE_utils.parseTable(enhancerFile,'\t')
  File "/home/mingyu.liu001/Software/ROSE-1.3.0/lib/ROSE_utils.py", line 45, in parseTable
    fh = open(fn)
FileNotFoundError: [Errno 2] No such file or directory: './EHMT1_ctrl//EHMT1_ctrl_merged_peaks_AllStitched.table.txt'

The command I used was:
module load python-3.8.6-gcc-10.2.0-l6v2aag 
module load samtools-1.10-gcc-10.2.0-gcazqa4
module load bedtools2-2.27.1-gcc-10.2.0-d5nov5h
module load r-4.0.2-gcc-9.3.0-agrxgnh
ROSE_main.py -g hg19 -i EHMT1_ctrl_merged_peaks.bed -r EHMT1_ctrl_merged_sorted.bam -o ./EHMT1_ctrl

In addition, I just want to confirm the default STITCHING_DISTANCE for this version, since I saw the file named "_5.0KB_STITCHED_". I remembered for previous package the default setting of STITCHING_DISTANCE is 12.5KB.

Thank you,
Mingyu

**Comment by madetunj** [comment]
X11 is a dependency in R. Your R version probably doesn't have png capabilities. This can be checked using the command `capabilities()` in R and at least the png capability should be TRUE.
```R
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
       TRUE        TRUE        TRUE        TRUE       FALSE        TRUE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
```
We have a docker image for ROSE, which may be convenient to use: `abralab/rose:v1.3.0`

Yes, the default STITCHING_DISTANCE for this version is 5000. It's probably a mistake during an update and will be changed shortly. Thanks for pointing this out. In the meantime, the stitch distance can be changed using the option `-stitch`
