### ISSUE TITLE
Is there any difference between "Stitched" and "Enhancers"

### ISSUE THREAD

**Issue by zxwang2019** [stjude/ROSE#19]
Hi,

I am currently running ROSE on my data to call super enhancers, and I found that the filename in our results is "*_ _peaks_SuperStitched.table.txt" or "*_peaks_AllStitched.table.txt". But in the previous versions, I notice that the output filename is "*_SuperEnhancers.table.txt"  or "*_AllEnhancers.table.txt", so, is there any essential difference between them?

Best,
Zixian

**Comment by madetunj** [comment]
Hi Zixian, Yes there's no difference between them. We only updated the filenames.

**Comment by zxwang2019** [comment]
> Hi Zixian, Yes there's no difference between them. We only updated the filenames.

Thank you for reply!

**Comment by zxwang2019** [comment]
> Hi Zixian, Yes there's no difference between them. We only updated the filenames.

Thank you for your reply!
