### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by AGunnell77** [stjude/ROSE#24]
Hi I have come across the following error during the geneMapper stage of ROSE:
I ran using 

ROSE_main.py  -g hg38 -i /enhancers__hg38.gff -r /sorted.bam -o /output/

The first stages were successful and I have the png plot of ranked stitched enhancers then it stopped with this error

MAKING TSS COLLECTION
Traceback (most recent call last):
  File "/data/scratch/DGE/DUDGE/MOPOPGEN/agunnell/ROSE//bin/ROSE_geneMapper.py",
    main()
  File "/data/scratch/DGE/DUDGE/MOPOPGEN/agunnell/ROSE//bin/ROSE_geneMapper.py",
    enhancerToGeneTable,geneToEnhancerTable = mapEnhancerToGene(annotFile,enhancile)
  File "/data/scratch/DGE/DUDGE/MOPOPGEN/agunnell/ROSE//bin/ROSE_geneMapper.py",
    closestGene = allEnhancerGenes[distList.index(min(distList))]
IndexError: list index out of range

Any help would be appreciated.
Thanks

**Comment by Mo-Shine** [comment]
hello，i encouraged the same problem, and i don’t how to solve it. do you solve this problem?

**Comment by WangYuzhou1996** [comment]
@Mo-Shine Hello，I encountered the same problem, after running ROSE_main,I didn't get the SuperEnhancers.table.txt file, and got the error:IndexError: list index out of range.
Did you solve the problem?

**Comment by erzakiev** [comment]
why closing the question without posting a solution
