### ISSUE TITLE
Info on how refs in /annotation/ were created

### ISSUE THREAD

**Issue by slsevilla** [stjude/ROSE#25]
Hi - I'm looking for information on how the references in the /annotation/ directory was created? I'm trying to create a T2T annotation and want to follow the same method as was done for the others.

Thanks!
-Samantha

**Comment by madetunj** [comment]
Hi, 
The annotation file is typically downloaded from UCSC table browser. 
For unrepresented genomes or regions, you will need a gene annotation file (in GTF or GFF) and use the following syntaxes below to convert it to the UCSC annotation format. More reference on this can be found [here](https://github.com/stjude/ROSE/blob/master/ROSE-local.sh#:~:text=mkdir%20%2Dp%20annotation,%22%24SPECIES%22_refseq.ucsc%22)
```
mkdir -p annotation
echo -e "#bin\tname\tchrom\tstrand\ttxStart\ttxEnd\tcdsStart\tcdsEnd\tX\tX\tX\t\tX\tname2" > annotation/$SPECIES"_refseq.ucsc"
awk -F'[\t ]' '{
  if($3=="transcript")
    print "0\t" $14 "\tchr" $1 "\t" $7 "\t" $4 "\t" $5 "\t" $4 "\t" $5 "\t.\t.\t.\t.\t" $18}' $GTFFILE | sed s/\"//g >> annotation/$SPECIES"_refseq.ucsc"
```

**Comment by slsevilla** [comment]
Hi – Thanks so much for your reply. I was able to create the file I needed.

-Samantha

**Comment by slsevilla** [comment]
Hi - I'm not the author of the tool, but can give some thoughts on your question.

> I would like to know, is it still generating the annotation file in the same way as above at this time?
I would imagine that yes, it would be the same.
>If we simply add the character ‘chr’ in front of the chromosome number, there may be some problems because the annotation file coordinates of the two genome annotations file are not quite the same.
If you're using UCSC to do the alignment, then yes, adding "chr" and using ENSMBL downstream is not going to give you the results you're looking for. Whatever you use for one, you should use for both.
> In addition, I tried this method to construct the annotation file needed for ROSE using the pig annotation file from the ensembl database and compared it with the pig annotation file downloaded from UCSC, and found that the number of rows in the two files differed by an order of magnitude (Ss11_refseq.ensembl contain 4614 rows and Ss11_refseq. ucsc contain 60955 rows), I know that each line represents a transcript, but I don't know why there is such a big difference between the annotation files of the two database sources.
The two databases are annotated differently, although they use the same assembly (if you're choosing the same db), and therefore differences are expected. There's a lot of literature on the differences, but here is one paper: https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-015-1308-8
