### ISSUE TITLE
Can ROSE be applied to process paired-end ChIP-seq data to identify super-enhancers?

### ISSUE THREAD

**Issue by Ren-Meng** [stjude/ROSE#26]

**Comment by Ren-Meng** [comment]
Hello,
Thanks for developing such a great tool!

I am going to apply it to process my paired-end ChIP-seq data to identify super-enhancers. I noticed that when mapping bam reads to gff regions, the bam reads were extended by 200bp.  In the case of paired-end data, as I understand it, It would be better to use the paired-end information to get the fragment length and compute the read density. 
Nevertheless, I would like to ask your opinion about processing the paired-end data.

Any help would be appreciated!

**Comment by madetunj** [comment]
ROSE is unable to infer the varied fragment lengths for paired-end data at this time, but yes it would be a better approach to infer read density with such data.

**Comment by Ren-Meng** [comment]
Thanks for your prompt reply!

Is it feasible to treat paired-end data as single-end data to identify super-enhancers using ROSE?
