### ISSUE TITLE
Find different

### ISSUE THREAD

**Issue by lanpangzi111** [stjude/ROSE#35]
Now I have two sets of data, one is the dosed experimental group and the other is the undosed group. I want to find the super enhancer of the difference between the two groups. Can you treat the undosed group as Control and consider SE calculated by ROSE as the difference SE

**Comment by madetunj** [comment]
Yes, you can use the undosed group as a control. Run ROSE separately on both groups, then compare the super-enhancers between them to identify differential SEs based on signal differences. This will highlight SEs affected by the dose.
