### ISSUE TITLE
Can we analyze multiple samples together to find consensus SE between them?

### ISSUE THREAD

**Issue by biobug16** [stjude/ROSE#5]
Hi [madetunj](https://github.com/madetunj)
I am trying to use ROSE to call Super Enhancer between the two subtypes of a cancer, where each group has 5 samples. But I have few doubts like:

Can I run this pipeline using all 5 samples together in order to identify consensus SE within each subtype and compare the two groups?

I also have another question, in the [readme file](https://github.com/stjude/ROSE/blob/master/README.md) and in the given command, what are these **bed file A** and **bed file B**?
ROSE-local.sh ["GTF file"] ["BAM file"] ["OutputDir"] ["feature type"] ["species"] ["bed fileA"] ["bed fileB"]

**Comment by abrahamb2** [comment]
We generally recommend treating each sample independently for ROSE input.  There are multiple approaches to comparing SEs called by ROSE in different samples, including combining the regions-of-interest and performing statistical analyses on signal quantified therein.  

BED files A and B refer only to ROSE-local.  We recommend using ROSE_main for most analyses.
