### ISSUE TITLE
SE calls with and without input-DNA bam file

### ISSUE THREAD

**Issue by ArashDepp** [stjude/ROSE#8]
In **rose_main.py**, there is an option to provide control bam file. I am wondering how much difference it would make to SE calls if control file is not available. My guess is that since MACS2 peaks would already take into account the control bam file, it shouldn't make major differences to SE calls with/without control bam file.
What would you say?
Thanks and best regards

**Comment by abrahamb2** [comment]
Using ROSE with or without input control set (-c) is expected to change the outputs.  The degree of this difference is unpredictable without testing.  Some contributors might be the ploidy of the cells, and the quality of the pulldown of the ranking factor.  If the control file is available and of high quality, we generally recommend using it for both peak-calling and ROSE.
